feat: add Log4j2 plugin to filter the stacktrace
Hapag-Lloyd/log4j2-filtered-stacktrace-plugin pull request #5
Opened 2024-03-16 09:27 UTC by kayman-mk

# Description

Adds the first version of the plugin. This is a copy of our internal repository. I adjusted the `pom.xml` and the package name.

# Checklist

- [x] My code follows the style guidelines of the project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation

2024-03-16 22:06 UTC, PascalFrenz requested changes

2024-03-16 22:06 UTC, PascalFrenz commented on pom.xml
> +            <url>https://github.com/Hapag-Lloyd/dist-comm-vis/blob/main/LICENSE</url>
Should be changed to Apache 2.0 as https://github.com/Hapag-Lloyd/log4j2-filtered-stacktrace-plugin/pull/1 changes the license too

2024-03-16 22:06 UTC, PascalFrenz commented on pom.xml
> +        <url>https://github.com/Hapag-Lloyd/dist-comm-vis/tree/main</url>
these links should point to this repository (https://github.com/Hapag-Lloyd/log4j2-filtered-stacktrace-plugin)

2024-03-16 22:06 UTC, PascalFrenz commented on src/test/java/com/hlag/logging/log4j2/FilteredStacktraceStackTraceJsonResolverUnitTest.java
> +        FilteredStacktraceExceptionResolver.setPackagesToRemoveFromStacktrace(List.of("com.hlag.fis.sales"));
change this package name to `com.hlag.logging.log4j2` or similar

2024-03-17 10:51 UTC, kayman-mk commented
Good spot. Everything fix. Tests still green.

2024-03-17 11:26 UTC, PascalFrenz commented on log4j2-stacktrace-filter.iml
This is an IntelliJ-specific file, committed unintentionally. I think we should add it to `.gitignore` too.

2024-03-17 11:27 UTC, kayman-mk commented on log4j2-stacktrace-filter.iml
Just checked the file. Seems to be good to have it as it includes the module definition only.

2024-03-17 11:30 UTC, kayman-mk commented on log4j2-stacktrace-filter.iml
Checked some other pages. LEt's get rid of the file.

2024-03-17 11:41 UTC, PascalFrenz approved these changes

2024-03-17 14:25 UTC, merged

2024-03-18 10:55 UTC, kayman-mk commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- `1.0.0`
- [GitHub release](https://github.com/Hapag-Lloyd/log4j2-filtered-stacktrace-plugin/releases/tag/1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: